### PR TITLE
[IMPROVE] Add tab behaviour logs and Tab_id for logs

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Closes:
 -  https://github.com/WideChat/Rocket.Chat/issues/1234
 - https://github.com/WideChat/Rocket.Chat/issues/1237

### CODE REVIEW

**Review by Shailesh351 — COMMENTED** [review]
@bhardwajaditya This looks good. Can you update the SDK dependency, please?

**Comment by bhardwajaditya** [comment]
@Shailesh351 done

**Review by Shailesh351 — APPROVED** [review]

**Comment by Shailesh351** [comment]
@bhardwajaditya FYI sometimes the window open event fails to log because of missing roomId;

Screenshot 2022-07-29 at 3 46 55 PM

**Comment by bhardwajaditya** [comment]
@Shailesh351 yes, that is expected behaviour. We discussed that we don't want to track non room associated tab events.

**Pull request merged**
